In [1]:
import json
import pandas as pd
from pandas import json_normalize
import requests

In [2]:
with open ("databangladeshi_users.json") as f:
    dataset = json.load(f)

In [20]:
flat_data = []

for user_data in dataset :
    flat_data.append({
        "userid" : user_data["user_id"],
        "purchases" : sum(user_data["purchases"]),
        "items" : len(user_data["purchases"]),
        "average" : sum(user_data["purchases"])/len(user_data["purchases"]),
        "location" : user_data["location"],
        "lastlogin" : user_data["last_login"],
        "loyalty" : user_data["loyalty"]
    })

df = pd.DataFrame(flat_data)
df.head()

   userid  purchases  items  average    location   lastlogin loyalty
0    1001       4931      4  1232.75     Barisal  2025-04-25  Bronze
1    1002       1137      2   568.50  Chittagong  2025-04-30  Bronze
2    1003       2483      2  1241.50    Rajshahi  2025-05-06  Bronze
3    1004       1986      3   662.00  Mymensingh  2025-03-24  Bronze
4    1005       4862      5   972.40      Khulna  2025-05-20  Bronze

In [13]:
data={
    "user_id": 1499,
    "purchases": [
      1164,
      290,
      772,
      235
    ],
    "location": "Barisal",
    "last_login": "2025-03-03",
    "loyalty": "Bronze"
     }

parsed = json_normalize(data)
parsed

   user_id              purchases location  last_login loyalty
0     1499  [1164, 290, 772, 235]  Barisal  2025-03-03  Bronze

In [14]:
response = requests.get("https://dummyjson.com/products")
data = response.json()
data
df = pd.json_normalize(data["products"])


df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,29.27,27.93,20.59,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,40,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,18.11,28.38,22.17,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,21.63,16.48,29.84,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png

In [15]:
df.columns

Index(['id', 'title', 'description', 'category', 'price', 'discountPercentage',
       'rating', 'stock', 'tags', 'brand', 'sku', 'weight',
       'warrantyInformation', 'shippingInformation', 'availabilityStatus',
       'reviews', 'returnPolicy', 'minimumOrderQuantity', 'images',
       'thumbnail', 'dimensions.width', 'dimensions.height',
       'dimensions.depth', 'meta.createdAt', 'meta.updatedAt', 'meta.barcode',
       'meta.qrCode'],
      dtype='object')